- name: check if present
  stat: path={{telegraf_dir}}
  register: running
- name: download telegraf
  local_action: get_url url=https://dl.influxdata.com/telegraf/releases/telegraf-{{telegraf_version}}_linux_amd64.tar.gz dest=/tmp/telegraf.tar.gz
  when: not (running.stat.exists)
- name: unpack telegraf
  unarchive: src=/tmp/telegraf.tar.gz dest=.
  when: not (running.stat.exists)
- name: copy script
  copy: src=restartTelegraf.sh dest=./restartTelegraf.sh mode=0775
- name: copy conf
  template: src=telegraf.conf dest=./telegraf.conf
- name: start telegraf
  command: ./restartTelegraf.sh
