version: '2.1'

services:

  app:
    build: ./app
    links:
      - "jobmanager:jobmanager"
      - "kafka:kafka"
      - "influxdb:influxdb"
      - "zookeeper:zookeeper"
    expose:
      - "8080"
    volumes:
      - ./app/conf:/conf
      - ${CODE_LOCATION}:/code-assembly.jar
  jobmanager:
    build: ./flink
    expose:
      - "6123"
      - "8081"
    command: jobmanager
    depends_on:
      - zookeeper
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    links:
      - "influxdb:influxdb"
      - "zookeeper:zookeeper"
    volumes:
      - ./flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml

  taskmanager:
    build: ./flink
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "influxdb:influxdb"
      - "jobmanager:jobmanager"
      - "kafka:kafka"
      - "zookeeper:zookeeper"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    ulimits:
      nproc: 70000
      nofile:
        soft: 70000
        hard: 70000

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - "zookeeper:zookeeper"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - "9200"
      - "9300"
    ulimits:
      nproc: 70000
      nofile:
        soft: 70000
        hard: 70000

  logstash:
    build: ./logstash
    links:
      - elasticsearch
      - kafka
    expose:
        - "5000"
    depends_on:
      - elasticsearch
      - kafka
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.1
    expose:
      - "5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/:/usr/share/kibana/config

  influxdb:
    build: ./influxdb
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    expose:
      - "2003/udp"
  grafana:
    build: ./grafana
    links:
      - "influxdb:influxdb"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/grafana

  nginx:
    build: ./nginx
    ports:
      - "8081:80"
    links:
      - kibana
      - grafana
      - app
      - jobmanager