- name: create dest dir
  file: path=esp-frontend state=directory mode=0755
- name: build ui
  local_action: script buildUi.sh

- name: create demo esp-bundle locally
  local_action: script createDemoBundle.sh
- name: copy esp-bundle
  copy: src=/tmp/esp-bundle-0.1-SNAPSHOT.tar.gz dest=esp-frontend
- name: unpack esp-bundle
  unarchive: src=~/esp-frontend/esp-bundle-0.1-SNAPSHOT.tar.gz dest=~/esp-frontend remote_src=yes

- name: copy config
  template: src=application.conf dest=esp-frontend
- name: copy log
  template: src=logback.xml dest=esp-frontend
- name: copy users
  template: src=users.conf dest=esp-frontend
- name: copy run
  template: src=run.sh dest=esp-frontend mode=0775
- name: run
  command: chdir=~/esp-frontend ./run.sh

- name: remove esp-bundle locally
  local_action: command rm /tmp/esp-bundle-0.1-SNAPSHOT.tar.gz
