- name: remove log4j
  file: path={{flink_dir}}/lib/log4j-1.2.17.jar state=absent
- name: remove log4j
  file: path={{flink_dir}}/lib/slf4j-log4j12-1.7.7.jar state=absent

- name: add logback-core
  local_action: get_url url={{nexus_url}}ch/qos/logback/logback-core/1.1.7/logback-core-1.1.7.jar dest=/tmp
- name: add logback-classic
  local_action: get_url url={{nexus_url}}ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar dest=/tmp
- name: add slf4j-log4j
  local_action: get_url url={{nexus_url}}org/slf4j/log4j-over-slf4j/1.7.21/log4j-over-slf4j-1.7.21.jar dest=/tmp

- name: copy logback-core
  copy: src=/tmp/logback-core-1.1.7.jar dest={{flink_dir}}/lib
- name: copy logback-classic
  copy: src=/tmp/logback-classic-1.1.7.jar dest={{flink_dir}}/lib
- name: copy slf4j-log4j
  copy: src=/tmp/log4j-over-slf4j-1.7.21.jar dest={{flink_dir}}/lib

- name: copy logging config
  template: src=logback.xml dest={{flink_dir}}/conf/logback.xml